### ISSUE TITLE
Floppy disk Dead Test works great on the II+ but won't always start on a //c (presumably IIe as well)

### ISSUE THREAD

**Issue by misterblack1** [misterblack1/appleII_deadtest#1]
I have done extensive testing with the language card version of the Dead Test on floppy, and it works every time on a II+. But on my //c, it often does strange things after the BASIC program loads the 2K ROM into F800 in the language card RAM. 

Sometimes the system will crash and just doing 300G will start it normally. Sometimes it just works properly. Other times it freezes and doesn't do anything. 

Once the ROM starts, the RAM tests run normally and without issue. 

I assume there is some AUX RAM register we need to set before trying to load the Dead Test binary into F800 in the language card space. This register may be randomly set at boot, but I'm not sure...

With enough tries it does get started.

**Comment by ki3v** [comment]
Adrian resolved a bug in disk loader, solving this issue.
