### ISSUE TITLE
RAM Issue Apple II+

### ISSUE THREAD

**Issue by vibr77** [misterblack1/appleII_deadtest#4]
Hello, 
so In the end I found out why I was having the ZP 00000 message on the screen:
- Bad rom chip with corrupted data 
- 1 Apple II that seems to have a wired RAM issue

Thanks for this ROM test that is really useful to find issue other soft can not.
I was trying to understand why the Language card from Iz8dwf was not working, and he spend quite a lot of time to help me debugging the card (that was doing great).

I have the following result 👍 
![IMG_7278 Large](https://github.com/user-attachments/assets/3d17b4d9-16c0-4aec-8168-0c9aa3a6161e)

And if I understand well I have C5, D5, E5, and C7,D7,E7 that are dead and swapping men chip or replacing with new ram does not change anything. 

Do you have an idea where I need to investigate.

Thanks 
Vincent

**Comment by vibr77** [comment]
BAD DRAM IC on D8, this ROM is incredible ! thanks 
The regular DRAM tester was not able to detect issue but this ROM does !

**Comment by ki3v** [comment]
I'm so pleased that this helped resolve your issue.  Well done on rescuing your machine!
